### ISSUE TITLE
Graph of RSSI / SNR values

### ISSUE THREAD

**Issue by GillesC** [RobinMeis/TTNmon-Frontend#1]
Are you planning to allow the users to see their RSSI/SNR values and also the overall RSSI/SNR trends of all devices?

**Comment by RobinMeis** [comment]
I'm not sure if this data would be useful. Thus I generated two graphs:
![rssi](https://user-images.githubusercontent.com/3150817/35687226-6ffc4422-076e-11e8-9e3f-173ab37955fb.png)
![snr](https://user-images.githubusercontent.com/3150817/35687227-702455ca-076e-11e8-85ab-b247fb2d6333.png)
How would you use or interpret them? The peaks in the first days are caused by the limited amount of nodes I had initially.

**Comment by GillesC** [comment]
Well,

I am currently building a LoRa simulator to monitor the energy consumption of nodes in different environments. One of the challenges I face is to convert a certain RSS to an SNR. That is why I want real measurements to enhance the framework.

**Comment by RobinMeis** [comment]
That sounds like a quite specific application. I wonder if it would be better for you to use the raw data (for each node). As I offer database dumps you could use it directly in your simulator or create custom graphs.
